"use client";
import { useEffect, useState } from "react";
import "../globals.css";
import "./admin.css";

type Item={menu_item_id:string;name:string;quantity:number;unit_price_cents:number};
type Order={id:string;customer_name:string;phone:string;email?:string;order_date:string;preferred_time:string;fulfillment:string;notes?:string;status:string;total_cents:number;created_at:string;items?:Item[]};
const statuses=["pending","confirmed","preparing","ready","completed","cancelled"];
export default function AdminPage(){
 const[orders,setOrders]=useState<Order[]>([]),[selected,setSelected]=useState<Order|null>(null),[loading,setLoading]=useState(true),[unauthorized,setUnauthorized]=useState(false);
 async function load(){const r=await fetch("/api/orders",{cache:"no-store"});if(r.status===401){setUnauthorized(true);setLoading(false);return}const d=await r.json();setOrders(d.orders||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function logout(){await fetch("/api/admin/logout",{method:"POST"});location.href="/admin/login"}
 async function openOrder(id:string){const r=await fetch(`/api/orders/${id}`,{cache:"no-store"});if(r.ok)setSelected((await r.json()).order)}
 async function update(id:string,status:string){const r=await fetch(`/api/orders/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});if(r.ok){setOrders(x=>x.map(o=>o.id===id?{...o,status}:o));if(selected?.id===id)setSelected({...selected,status})}}
 if(unauthorized)return <main className="admin-page shell"><div className="admin-empty"><h2>Sign in required.</h2><a className="primary" href="/admin/login">Open kitchen login <span>→</span></a></div></main>;
 const active=orders.filter(o=>["pending","confirmed","preparing"].includes(o.status));
 return <main className="admin-page shell"><header className="admin-nav"><a className="brand" href="/"><span>Z</span> Zee&apos;s Kitchen</a><div><a href="/">View storefront →</a><button className="admin-logout" onClick={logout}>Sign out</button></div></header><div className="admin-heading"><div><p className="eyebrow">KITCHEN DASHBOARD</p><h1>Good evening, Zee.</h1><p>Here&apos;s what&apos;s happening with your orders.</p></div></div><section className="stats"><div><span>Active orders</span><strong>{active.length}</strong></div><div><span>Total orders</span><strong>{orders.length}</strong></div><div><span>Revenue</span><strong>${(orders.reduce((s,o)=>s+o.total_cents,0)/100).toFixed(2)}</strong></div></section><section className="orders"><p className="eyebrow">ORDER QUEUE</p><h2>Recent orders</h2>{loading?<div className="admin-empty">Loading orders…</div>:!orders.length?<div className="admin-empty">No orders yet.</div>:<div className="order-table">{orders.map(o=><article className="admin-order" key={o.id} onClick={()=>openOrder(o.id)}><div><strong>#{o.id.slice(0,8).toUpperCase()}</strong><span>{o.customer_name}</span></div><span>{o.fulfillment}</span><select className={`status ${o.status}`} value={o.status} onClick={e=>e.stopPropagation()} onChange={e=>update(o.id,e.target.value)} aria-label={`Update order ${o.id}`}>{statuses.map(s=><option key={s} value={s}>{s}</option>)}</select><strong>${(o.total_cents/100).toFixed(2)}</strong></article>)}</div>}</section>{selected&&<div className="order-modal" role="dialog" aria-modal="true"><div className="order-modal-card"><button className="close" onClick={()=>setSelected(null)} aria-label="Close order">×</button><p className="eyebrow">ORDER #{selected.id.slice(0,8).toUpperCase()}</p><h2>{selected.customer_name}</h2><div className="detail-grid"><span>Phone<strong>{selected.phone}</strong></span><span>Order date<strong>{selected.order_date} · {selected.preferred_time}</strong></span><span>Fulfillment<strong>{selected.fulfillment}</strong></span><span>Status<strong>{selected.status}</strong></span></div><div className="detail-items">{selected.items?.map(i=><div key={i.menu_item_id}><span>{i.name} × {i.quantity}</span><strong>${(i.unit_price_cents*i.quantity/100).toFixed(2)}</strong></div>)}</div>{selected.notes&&<p className="notes"><b>Notes</b>{selected.notes}</p>}<button className="primary" onClick={()=>setSelected(null)}>Close <span>×</span></button></div></div>}</main>
}
