"use client";
import {useEffect,useState} from "react";

type OneSignalInstance={User:{addTag:(key:string,value:string)=>void};Notifications:{permission:boolean;requestPermission:()=>Promise<void>|void}};

declare global{interface Window{OneSignalDeferred?:Array<(OneSignal:OneSignalInstance)=>void>}}

export default function AdminNotifications(){const[ready,setReady]=useState(false),[ios,setIos]=useState(false),[standalone,setStandalone]=useState(false),[permission,setPermission]=useState(false),[open,setOpen]=useState(false),[dismissed,setDismissed]=useState(false),[error,setError]=useState("");
 useEffect(()=>{let active=true;const ua=navigator.userAgent||"";const apple=/iPhone|iPad|iPod/i.test(ua);const standaloneMode=window.matchMedia("(display-mode: standalone)").matches||(navigator as Navigator&{standalone?:boolean}).standalone===true;setIos(apple);setStandalone(standaloneMode);const dismissedAt=Number(localStorage.getItem("zees-notification-prompt-dismissed")||0);setDismissed(Date.now()-dismissedAt<86400000);
 fetch("/api/admin/notifications/status",{cache:"no-store"}).then(r=>{if(!r.ok)throw Error("unauthorized");return r.json()}).then(()=>{window.OneSignalDeferred=window.OneSignalDeferred||[];window.OneSignalDeferred.push(async OneSignal=>{if(!active)return;OneSignal.User.addTag("role","admin");setPermission(!!OneSignal.Notifications.permission);setReady(true);if(!OneSignal.Notifications.permission&&!dismissedAt)setOpen(true)})}).catch(()=>{});return()=>{active=false}},[]);
 async function enable(){setError("");window.OneSignalDeferred=window.OneSignalDeferred||[];window.OneSignalDeferred.push(async OneSignal=>{try{await OneSignal.Notifications.requestPermission();setPermission(!!OneSignal.Notifications.permission);if(OneSignal.Notifications.permission){setOpen(false);localStorage.removeItem("zees-notification-prompt-dismissed")}}catch{setError("We couldn't open the notification permission. Please try again from this device.")}})}
 if(!ready||permission)return null;const dismiss=()=>{localStorage.setItem("zees-notification-prompt-dismissed",String(Date.now()));setDismissed(true);setOpen(false)};if(!open||dismissed)return <button onClick={()=>{setDismissed(false);setOpen(true)}} style={{position:"fixed",right:16,bottom:16,zIndex:50,border:0,borderRadius:999,padding:"12px 16px",background:"#111",color:"#fff",fontWeight:700,boxShadow:"0 10px 30px rgba(0,0,0,.18)"}}>🔔 Enable alerts</button>;
 return <div style={{position:"fixed",inset:0,zIndex:100,background:"rgba(0,0,0,.42)",display:"grid",placeItems:"end center",padding:16}}><div style={{width:"min(520px,100%)",background:"#fff",borderRadius:24,padding:"24px 22px",boxShadow:"0 20px 70px rgba(0,0,0,.28)"}}><div style={{fontSize:30}}>🔔</div><h2 style={{margin:"8px 0 6px",fontSize:25}}>Never miss a new order.</h2><p style={{margin:"0 0 18px",color:"#68635d",lineHeight:1.5}}>Get an instant Zee&apos;s Kitchen alert when a customer places an order or requests a booking.</p>{ios&&!standalone?<><div style={{background:"#f6f3ed",borderRadius:16,padding:16,lineHeight:1.55,fontSize:14}}><strong>On iPhone, do this once:</strong><br/>1. Tap the <b>Share</b> button in your browser.<br/>2. Choose <b>Add to Home Screen</b>.<br/>3. Open <b>Zee&apos;s Kitchen</b> from your Home Screen.<br/>4. Come back here and tap <b>Enable notifications</b>.</div><button onClick={dismiss} style={{width:"100%",marginTop:14,padding:14,border:0,borderRadius:12,background:"#111",color:"#fff",fontWeight:700}}>I&apos;ll add it to Home Screen</button></>:<><button onClick={enable} style={{width:"100%",padding:15,border:0,borderRadius:12,background:"#111",color:"#fff",fontWeight:700}}>Enable notifications</button>{error&&<p style={{color:"#b42318",fontSize:13}}>{error}</p>}</>}<button onClick={dismiss} style={{width:"100%",marginTop:8,padding:12,border:0,background:"transparent",color:"#777"}}>Not now</button></div></div>}
